[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "duckdb>=1.3.1",
    "isort>=6.0.1",
    "pylint>=3.3.7",
    "streamlit>=1.46.0",
]
